# This Vagrantfile can be used to install package from a local BaGet source to a .NET project
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"
    ubuntu.vm.network "private_network", ip: "192.168.50.4"

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
    end

    ubuntu.vm.provision "shell", privileged: true, inline: <<-SHELL
      echo "Starting provisioning..."

      wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      dpkg -i packages-microsoft-prod.deb
      apt-get update

      wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      apt-get install -y dotnet-sdk-8.0

      HOST_IP=$(ip route | awk 'NR==1 {print $3}')
      echo "Host IP detected as $HOST_IP"
      
      wget http://$HOST_IP:5000/v3/package/dvashchilina/1.0.0/dvashchilina.1.0.0.nupkg -O dvashchilina.1.0.0.nupkg
      echo "Downloaded dvashchilina.1.0.0.nupkg."

      echo "Creating a local NuGet source..."
      mkdir -p /home/vagrant/nuget-local
      cp dvashchilina.1.0.0.nupkg /home/vagrant/nuget-local/

      echo "Clearing NuGet cache..."
      dotnet nuget locals all --clear

      echo "Deleting existing App directory if it exists..."
      rm -rf /home/vagrant/App

      echo "Creating a new .NET project..."
      dotnet new console -o /home/vagrant/App
      cd /home/vagrant/App

      echo "Setting correct permissions for the App directory..."
      sudo chown -R vagrant:vagrant /home/vagrant/App
      sudo chmod -R 755 /home/vagrant/App

      echo "Removing existing local NuGet source if it exists..."
      dotnet nuget remove source local-source

      echo "Configuring the project to use the local NuGet source..."
      dotnet nuget add source /home/vagrant/nuget-local -n local-source

      echo "Adding the downloaded package to the project..."
      dotnet add package dvashchilina --source local-source

      echo "Provisioning complete."
    SHELL
  end
end